import {
  CustomerMaster,
  SupplierMaster,
  PurchaseRequest,
  GoodsReceiptLog,
  WorkOrderSpk,
  LeaveRequest,
  WasteRecord,
  EComplaintTicket,
  VendorInvoiceAp,
  ArPaymentRecord,
} from '../types';

export const INITIAL_CUSTOMERS: CustomerMaster[] = [
  {
    id: 'CUST-001',
    customerCode: 'CUST-ADM-001',
    companyName: 'PT Astra Daihatsu Motor (Plant Sunter)',
    customerStatus: 'OLD',
    businessType: 'Automotive Manufacturing',
    taxTransactionCode: '01', // Normal taxable delivery
    npwp: '01.234.567.8-012.000',
    nik: '3275012345670001',
    billingAddress: 'Jl. Danau Sunter Selatan Blok O5, Tanjung Priok, Jakarta Utara',
    shippingAddress: 'Plant Sunter Assembly Hall 2, Jakarta Utara',
    paymentTerm: 'Net 45 Hari',
    creditLimit: 500000000,
    contactPerson: 'Bapak Gunawan (Procurement Section Head)',
    phone: '+62 21 6510300',
    email: 'gunawan.proc@daihatsu.astra.co.id',
    businessUnit: 'INDUSTRIES',
    createdAt: '2025-01-10',
  },
  {
    id: 'CUST-002',
    customerCode: 'CUST-YMH-002',
    companyName: 'PT Yamaha Indonesia Motor Mfg',
    customerStatus: 'OLD',
    businessType: 'Automotive 2-Wheeler',
    taxTransactionCode: '01',
    npwp: '01.444.888.2-054.000',
    billingAddress: 'Jl. DR. KRT Radjiman Widyodiningrat, Pulo Gadung, Jakarta Timur',
    shippingAddress: 'Warehouse Part Receiving Gate 3, Pulo Gadung',
    paymentTerm: 'Net 30 Hari',
    creditLimit: 350000000,
    contactPerson: 'Ibu Ratna (Supply Chain)',
    phone: '+62 21 4600122',
    email: 'ratna.sc@yamaha-motor.co.id',
    businessUnit: 'INDUSTRIES',
    createdAt: '2025-02-14',
  },
  {
    id: 'CUST-003',
    customerCode: 'CUST-SMS-003',
    companyName: 'PT Samsung Electronics Indonesia',
    customerStatus: 'NEW',
    businessType: 'Consumer Electronics & Display',
    taxTransactionCode: '07', // Kawasan Berikat PPN Dibebaskan
    npwp: '01.999.111.4-412.000',
    billingAddress: 'Kawasan Industri Jababeka Tahap 2, Cikarang, Bekasi',
    shippingAddress: 'SMD Line Receiving Dock Cikarang Plant',
    paymentTerm: 'Net 60 Hari (Fasilitas KB)',
    creditLimit: 750000000,
    contactPerson: 'Mr. Lee / Pak Hendri',
    phone: '+62 21 8983000',
    email: 'hendri.vendor@samsung.com',
    businessUnit: 'INDUSTRIES',
    createdAt: '2026-03-01',
  },
];

export const INITIAL_SUPPLIERS: SupplierMaster[] = [
  {
    id: 'SUPP-001',
    supplierCode: 'SUPP-NPP-001',
    supplierName: 'Nippon Polymer & Chemical Corp Tokyo',
    npwp: '99.888.777.6-091.000',
    address: 'Chiyoda-ku, Marunouchi 1-Chome, Tokyo, Japan',
    phone: '+81 3 5555 0192',
    email: 'sales-asia@nippon-polymer.co.jp',
    contactPerson: 'Mr. Kenji Sato',
    paymentTerm: 'LC 60 Days / TT DP 30%',
    bankName: 'Sumitomo Mitsui Banking Corporation (SMBC)',
    bankAccountNumber: '8910-2391-0021-JPY',
    businessUnit: 'INDUSTRIES',
    status: 'ACTIVE',
  },
  {
    id: 'SUPP-002',
    supplierCode: 'SUPP-ASC-002',
    supplierName: 'PT Asahimas Chemical Cilegon',
    npwp: '01.002.394.1-411.000',
    address: 'Kawasan Industri Anyer KM 122, Cilegon, Banten',
    phone: '+62 254 601252',
    email: 'orders@asahimaschem.co.id',
    contactPerson: 'Bapak Bambang Supriyadi',
    paymentTerm: 'Net 30 Hari',
    bankName: 'Bank Central Asia (BCA) KCU Cilegon',
    bankAccountNumber: '295-0019283',
    businessUnit: 'INDUSTRIES',
    status: 'ACTIVE',
  },
  {
    id: 'SUPP-003',
    supplierCode: 'SUPP-TRY-003',
    supplierName: 'Toray Advanced Materials & Film Tokyo',
    npwp: '99.112.334.5-092.000',
    address: 'Nihonbashi-Muromachi, Chuo-ku, Tokyo, Japan',
    phone: '+81 3 3245 5111',
    email: 'films.export@toray.co.jp',
    contactPerson: 'Ms. Yoko Tanaka',
    paymentTerm: 'CAD / Net 45 Days',
    bankName: 'MUFG Bank Tokyo',
    bankAccountNumber: '0129-8831-4410',
    businessUnit: 'INDUSTRIES',
    status: 'ACTIVE',
  },
];

export const INITIAL_PRS: PurchaseRequest[] = [
  {
    id: 'PR-2026-001',
    prNumber: 'PR/PPIC/2026/09/0081',
    requestedBy: 'Agus Santoso (PPIC Planner)',
    department: 'PPIC Plant Cikarang',
    itemCode: 'RM-BOPP-JMB',
    itemName: 'BOPP Jumbo Roll Film 1280mm x 4000m (50 µm)',
    quantity: 24,
    unit: 'Jumbo Roll',
    requiredDate: '2026-09-18',
    priority: 'HIGH',
    status: 'APPROVED',
    purpose: 'Buffer pengaman pemenuhan SPK pesanan pita perekat Daihatsu & Astra',
    businessUnit: 'INDUSTRIES',
    createdAt: '2026-09-08',
  },
  {
    id: 'PR-2026-002',
    prNumber: 'PR/PPIC/2026/09/0085',
    requestedBy: 'Agus Santoso (PPIC Planner)',
    department: 'PPIC Plant Cikarang',
    itemCode: 'RM-ACR-RESIN',
    itemName: 'Solvent Acrylic Pressure Sensitive Adhesive Resin Drum',
    quantity: 12,
    unit: 'Drum 200L',
    requiredDate: '2026-09-22',
    priority: 'URGENT',
    status: 'REQUESTED',
    purpose: 'Kebutuhan mesin Coating Lini 1 untuk run produksi minggu ke-3 September',
    businessUnit: 'INDUSTRIES',
    createdAt: '2026-09-10',
  },
  {
    id: 'PR-2026-003',
    prNumber: 'PR/PPIC/2026/09/0089',
    requestedBy: 'Bambang Irawan (Warehouse)',
    department: 'Packaging & Warehouse',
    itemCode: 'PKG-BOX-KFT',
    itemName: 'Karton Boks Kraft St. Morita 380 x 280 x 300 mm',
    quantity: 1500,
    unit: 'Pcs',
    requiredDate: '2026-09-25',
    priority: 'NORMAL',
    status: 'DRAFT',
    purpose: 'Kemasan packing produk ekspor dan pengiriman lokal',
    businessUnit: 'INDUSTRIES',
    createdAt: '2026-09-11',
  },
];

export const INITIAL_GOODS_RECEIPTS: GoodsReceiptLog[] = [
  {
    id: 'LOG-2026-001',
    logNumber: 'LOG/WH/2026/09/0142',
    poNumber: 'PO/PUR/2026/09/0142',
    supplierName: 'Nippon Polymer & Chemical Corp',
    deliveryNoteNumber: 'SJ-NPP-JKT-8921',
    vendorTruckPlate: 'B 9812 UYX',
    driverName: 'Pak Dedi (Trans Express)',
    receiptDate: '2026-09-10 10:15',
    receivedBy: 'Eko Prasetyo (Gudang Bahan Baku)',
    itemCode: 'RM-BOPP-JMB',
    itemName: 'BOPP Jumbo Roll Film 1280mm x 4000m (50 µm)',
    lotNumber: 'LOT-NPP-202609-08',
    qtyDelivered: 12,
    unit: 'Jumbo Roll',
    isIqcTriggered: true,
    iqcStatus: 'PASS',
    businessUnit: 'INDUSTRIES',
  },
  {
    id: 'LOG-2026-002',
    logNumber: 'LOG/WH/2026/09/0148',
    poNumber: 'PO/PUR/2026/09/0149',
    supplierName: 'PT Asahimas Chemical Cilegon',
    deliveryNoteNumber: 'SJ-ASC-CLG-4019',
    vendorTruckPlate: 'A 9012 BB',
    driverName: 'Pak Rahmat',
    receiptDate: '2026-09-11 14:30',
    receivedBy: 'Eko Prasetyo (Gudang Bahan Baku)',
    itemCode: 'RM-ACR-RESIN',
    itemName: 'Solvent Acrylic Pressure Sensitive Adhesive Resin Drum',
    lotNumber: 'LOT-ASC-202609-14',
    qtyDelivered: 6,
    unit: 'Drum 200L',
    isIqcTriggered: true,
    iqcStatus: 'PENDING',
    businessUnit: 'INDUSTRIES',
  },
];

export const INITIAL_SPKS: WorkOrderSpk[] = [
  {
    id: 'SPK-2026-001',
    spkNumber: 'SPK/PRD/2026/09/0034',
    customerIoRef: 'IO/SMI/2026/09/0231 (Daihatsu)',
    itemCode: 'SM-MSK-KFT24',
    itemName: 'Automotive Masking Tape High-Temp 150°C 24mm x 50m',
    targetQuantity: 4800,
    producedGoodQty: 4650,
    producedNgQty: 50,
    unit: 'Roll',
    targetWidthMm: 24,
    targetLengthM: 50,
    targetMicron: 135,
    productionLine: 'Lini Slitting Otomatis 02',
    operatorName: 'Wahyu Hidayat',
    spkStatus: 'ON_PROCESS',
    startDate: '2026-09-10 08:00',
    dueDate: '2026-09-12 17:00',
    rawMaterialLotChecked: true,
    businessUnit: 'INDUSTRIES',
  },
  {
    id: 'SPK-2026-002',
    spkNumber: 'SPK/PRD/2026/09/0035',
    customerIoRef: 'IO/SMI/2026/09/0233 (Yamaha)',
    itemCode: 'SM-DCT-IND50',
    itemName: 'Heavy Duty Industrial Cloth Duct Tape Silver 50mm x 25m',
    targetQuantity: 2000,
    producedGoodQty: 2000,
    producedNgQty: 20,
    unit: 'Roll',
    targetWidthMm: 50,
    targetLengthM: 25,
    targetMicron: 220,
    productionLine: 'Lini Rewinder & Slitting 01',
    operatorName: 'Joko Susilo',
    spkStatus: 'COMPLETED',
    startDate: '2026-09-08 08:00',
    dueDate: '2026-09-09 16:00',
    rawMaterialLotChecked: true,
    businessUnit: 'INDUSTRIES',
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'LV-2026-001',
    employeeName: 'Wahyu Hidayat',
    employeeNik: 'NIK-2022-108',
    department: 'Produksi - Slitting 02',
    leaveType: 'CUTI_TAHUNAN',
    startDate: '2026-09-18',
    endDate: '2026-09-19',
    durationDays: 2,
    reason: 'Acara keluarga di kampung halaman (Solo)',
    status: 'APPROVED',
    approvedBy: 'Siti Rahmadani (HRD Manager)',
    createdAt: '2026-09-09',
  },
  {
    id: 'LV-2026-002',
    employeeName: 'Rian Pratama',
    employeeNik: 'NIK-2021-089',
    department: 'Quality Control Lab',
    leaveType: 'SAKIT_SURAT_DOKTER',
    startDate: '2026-09-11',
    endDate: '2026-09-12',
    durationDays: 2,
    reason: 'Demam tinggi & radang tenggorokan (Surat Klinik Medika Cikarang terlampir)',
    status: 'APPROVED',
    approvedBy: 'Siti Rahmadani (HRD Manager)',
    attachmentName: 'Surat_Dokter_Rian_Pratama.pdf',
    createdAt: '2026-09-11',
  },
  {
    id: 'LV-2026-003',
    employeeName: 'Dimas Aditya',
    employeeNik: 'NIK-2021-055',
    department: 'Sales & Marketing',
    leaveType: 'IZIN_KEPERLUAN_KHUSUS',
    startDate: '2026-09-24',
    endDate: '2026-09-24',
    durationDays: 1,
    reason: 'Urusan administrasi kependudukan di Samsat & Dukcapil',
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-12',
  },
];

export const INITIAL_WASTES: WasteRecord[] = [
  {
    id: 'WST-2026-001',
    ticketNumber: 'WST/RM/2026/09/0014',
    wasteType: 'RAW_MATERIAL_WASTE',
    itemCode: 'RM-BOPP-JMB',
    itemName: 'BOPP Jumbo Roll Film 1280mm',
    lotNumber: 'LOT-NPP-202609-02',
    quantity: 42.5,
    unit: 'Kg',
    severity: 'MINOR',
    rootCause: 'Kerutan tepi (edge trim curl) saat proses unwinding roll awal',
    correctiveAction: 'Penyesuaian tension brake dan eliminasi sisa trim roll',
    preventiveAction: 'Pemeriksaan kelurusan poros chucking mesin slitting sebelum start',
    reportedBy: 'Wahyu Hidayat',
    dateReported: '2026-09-09',
    businessUnit: 'INDUSTRIES',
  },
  {
    id: 'WST-2026-002',
    ticketNumber: 'WST/FG/2026/09/0009',
    wasteType: 'FINISHED_PRODUCT_WASTE',
    itemCode: 'SM-MSK-KFT24',
    itemName: 'Automotive Masking Tape High-Temp 24mm',
    lotNumber: 'LOT-IND-202609-08',
    quantity: 18,
    unit: 'Roll',
    severity: 'MAJOR',
    rootCause: 'Pisau slitter tumpul mengakibatkan serabut potongan pada sisi samping roll',
    correctiveAction: 'Penggantian mata pisau carbide circular slitter baru',
    preventiveAction: 'Jadwal penajaman mata pisau berkala setiap 50,000 meter lari',
    reportedBy: 'Rian Pratama (QC Inspector)',
    dateReported: '2026-09-10',
    businessUnit: 'INDUSTRIES',
  },
];

export const INITIAL_COMPLAINTS: EComplaintTicket[] = [
  {
    id: 'CMP-2026-001',
    ticketNumber: 'CMP/SMI/2026/09/0012',
    customerName: 'PT Astra Daihatsu Motor (Plant Sunter)',
    deliveryOrderNumber: 'DO/SMI/2026/09/0112',
    invoiceNumber: 'INV/SM/2026/09/0819',
    complaintType: 'UNSUITABLE_QUALITY_NG',
    correctiveActionRequested: 'REPLACEMENT_OF_GOODS',
    description: 'Ditemukan 1 box (40 roll) masking tape memiliki daya rekat kurang konsisten saat suhu oven 140°C pada body stamping primer.',
    targetDepartment: 'QC',
    photoEvidenceUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=300',
    qcReinspectionStatus: 'INSPECTED_NG_CONFIRMED',
    rmaNumber: 'RMA/SMI/2026/09/0005',
    debitNoteNumber: 'DN/FIN/2026/09/0002',
    status: 'INVESTIGATING',
    createdAt: '2026-09-10',
    businessUnit: 'INDUSTRIES',
  },
  {
    id: 'CMP-2026-002',
    ticketNumber: 'CMP/SMI/2026/09/0013',
    customerName: 'PT Yamaha Indonesia Motor Mfg',
    deliveryOrderNumber: 'DO/SMI/2026/09/0113',
    invoiceNumber: 'INV/SM/2026/09/0820',
    complaintType: 'UNSUITABLE_DOCUMENT',
    correctiveActionRequested: 'REPLACEMENT_OF_DOCUMENTS',
    description: 'Nomor Faktur Pajak pada invoice cetak terdapat kesalahan 1 digit angka Seri Faktur Pajak.',
    targetDepartment: 'MARKETING',
    qcReinspectionStatus: 'INSPECTED_REJECTED',
    status: 'RESOLVED',
    createdAt: '2026-09-11',
    businessUnit: 'INDUSTRIES',
  },
];

export const INITIAL_VENDOR_INVOICES: VendorInvoiceAp[] = [
  {
    id: 'AP-2026-001',
    invoiceNumber: 'INV-SUPP-NPP-8910',
    poNumber: 'PO/PUR/2026/09/0142',
    supplierName: 'Nippon Polymer & Chemical Corp',
    invoiceDate: '2026-09-08',
    dueDate: '2026-10-23',
    totalAmount: 485000000,
    taxAmount: 0, // EXIM KB Fasilitas
    status: 'PARTIALLY_PAID', // DP 30% paid
    paymentTerm: 'CAD / LC 45 Hari',
    businessUnit: 'INDUSTRIES',
  },
  {
    id: 'AP-2026-002',
    invoiceNumber: 'INV-SUPP-ASC-4412',
    poNumber: 'PO/PUR/2026/09/0149',
    supplierName: 'PT Asahimas Chemical Cilegon',
    invoiceDate: '2026-09-10',
    dueDate: '2026-10-10',
    totalAmount: 162500000,
    taxAmount: 17875000, // PPN 11%
    status: 'UNPAID',
    paymentTerm: 'Net 30 Hari',
    businessUnit: 'INDUSTRIES',
  },
];

export const INITIAL_AR_PAYMENTS: ArPaymentRecord[] = [
  {
    id: 'AR-2026-001',
    receiptNumber: 'OR/BCA/2026/09/042',
    invoiceNumber: 'INV/SM/2026/09/0819',
    customerName: 'PT Astra Daihatsu Motor',
    paymentDate: '2026-09-11',
    amountPaid: 100000000,
    paymentMethod: 'BCA_VIRTUAL_ACCOUNT',
    bankRef: 'TRF-BCA-ADM-890213',
    reconciled: true,
    notes: 'Pembayaran termin 1 atas pengiriman DO Multi-Item Tahap 1',
    businessUnit: 'INDUSTRIES',
  },
];
